server:
  port: 6000

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_USER_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  cloud:
    consul:
      host: 127.0.0.1
      discovery:
        #        instanceId: "${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}"
        instanceId: ${spring.application.name}-${server.port}
        prefer-ip-address: true
        health-check-critical-timeout: "1m"
      config:
        enabled: false
app:
  jwt-secret: AvHGRK8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadweheufHNyG
  jwt-expiration-milliseconds: 3600000


management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true