apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: default
  labels:
    name: book-service
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 3333
      protocol: TCP
  selector:
    app: book-service
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
#      annotations:
#        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      containers:
        - name: book-service
          image: amtlh/book-service:1.0.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 7000
          env:
            - name: spring.cloud.consul.host
              value: "$(CONSUL_SERVER_SVC_SERVICE_HOST)"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: book-postgres-db-host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: book-postgres-db-name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: book-mongo-db-name
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: book-mongo-db-host
            - name: DISCOVERY_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: discovery-service-host
            - name: DISCOVERY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: discovery-service-port