apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  book-postgres-db-host: postgres-book
  book-postgres-db-name: book_db
  book-mongo-db-host: mongo-img-service
  book-mongo-db-name: Book
  discovery-service-host: consul-service
  discovery-service-port: "8500"
  user-postgres-db-host: postgres-userdb
  user-postgres-db-name: userdb_db


