apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: default
  labels:
    name: gateway
spec:
  ports:
    - nodePort: 30168
      port: 8080
      targetPort: 9191
      protocol: TCP
  selector:
    app: gateway
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: amtlh/gateway:1.0.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9191
          env:
            - name: spring.cloud.consul.host
              value: "$(CONSUL_SERVER_SVC_SERVICE_HOST)"

