apiVersion: v1
kind: Service
metadata:
  name: mail-service
  namespace: default
  labels:
    name: mail-service
spec:
  ports:
    - nodePort: 31164
      port: 8082
      targetPort: 5000
      protocol: TCP
  selector:
    app: mail-service
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
        - name: mail-service
          image: amtlh/mail:1.0.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 1000


