---
apiVersion: v1
kind: Service
metadata:
  name: postgres-book
  labels:
    app: postgres-book
    tier: database-book
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-book
    tier: database-book
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim-book
  labels:
    app: postgres-book
    tier: database-book
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-book
  labels:
    app: postgres-book
    tier: database-book

spec:
  selector:
    matchLabels:
      app: postgres-book
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-book
        tier: database-book

    spec:
      containers:
        - name: postgres
          image: postgres:16.2
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_DB
              value: book_db
            - name: POSTGRES_USER
              value: postuser
            - name: POSTGRES_PASSWORD
              value: qwerty
          ports:
            - containerPort: 5432
              name: postgres-book
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistance-book
      volumes:
        - name: postgres-persistance-book
          persistentVolumeClaim:
            claimName: postgres-pv-claim-book