apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  labels:
    app: book-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: amtlh/book-service:1.0.0
          ports:
            - containerPort: 7000
          env:
            - name: DATASOURCE_HOST
              value: 192.168.100.8




