apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
  labels:
    name: user-service
spec:
  ports:
    - nodePort: 30164
      port: 8082
      targetPort: 1000
      protocol: TCP
  selector:
    app: user-service
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: amtlh/user-service:1.0.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 1000
          env:
            - name: spring.cloud.consul.host
              value: "$(CONSUL_SERVER_SVC_SERVICE_HOST)"
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: user-postgres-db-host
            - name: POSTGRES_USER_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: user-postgres-db-name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
            - name: DISCOVERY_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: discovery-service-host
            - name: DISCOVERY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: discovery-service-port
