server:
  port: 9191

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: 127.0.0.1
      discovery:
        #        instanceId: "${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}"
        instanceId: ${spring.application.name}-${server.port}
        prefer-ip-address: true
        health-check-critical-timeout: "1m"
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthFilter

        #          filters:
        #            - name: CircuitBreaker
        #              args:
        #                name: userServiceCB
        #                fallbackUri: forward:/fallback/user-service

        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**
          filters:
            - AuthFilter

        - id: auth-server
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthFilter
jwt:
  secret: AvHGRK8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadweheufHNyG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true