#server:
#  port: 7000
#
#spring:
#  application:
#    name: book-service
#  datasource:
#    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
#  data:
#    mongodb:
#      host: ${MONGO_HOST}
#      port: 27017
#      database: ${MONGO_DB}
#
#  cloud:
#    consul:
#      host: 127.0.0.1
#      discovery:
#        instanceId: ${spring.application.name}-${server.port}
#        prefer-ip-address: true
#        health-check-critical-timeout: "1m"
#      config:
#        enabled: false
#  servlet:
#    multipart:
#      max-file-size: 2024MB
#      max-request-size: 2024MB
#      enabled: true
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  prometheus:
#    metrics:
#      export:
#        enabled: true