server:
  port: 7000

#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#      url:  jdbc:postgresql://localhost:5432/book_db

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Book
  servlet:
    multipart:
      max-file-size: 2024MB
      max-request-size: 2024MB
      enabled: true
  application:
    name: book-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

#management:
#    jmx:
#      exposure:
#        include: *
