services:
  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_DB: "user_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"



