services:
  postgres:
    image: "postgres:16.0"
    restart: always
    environment:
      POSTGRES_DB: "user_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "54322:5432"



