services:
#  book-service:
#    container_name: book-service
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - postgres_db
#      - mongo_db
#    restart: on-failure
#    ports:
#      - "7000:7000"
#    networks:
#      book-lib-net:

  postgres_db:
#    container_name: postgres_db
    container_name: postgres_loc_db
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: "book_db"
      POSTGRES_USER: "postuser"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5432:5432"
#    networks:
#      book-lib-net:

  mongo_db:
    container_name: mongo_loc_db
    image: mongo
    ports:
      - 27017:27017
#    networks:
#      book-lib-net:
#
#networks:
#  book-lib-net:
