services:
  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_DB: "email_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "54325:5432"



